version: '3'

services:
  database:
    container_name: fifa_db
    build: ./db
    environment:
      MYSQL_DATABASE: fifa
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root"]
      timeout: 20s
      retries: 10

  frontend:
    container_name: frontend
    build: ./frontend
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "3000:3000"

  backend:
    container_name: backend
    build: ./backend
    depends_on:
      database:
        condition: service_healthy
    environment:
      DB_USER: root
      DB_PASSWORD: root
      DB_HOST: database
      DB_NAME: fifa
      DB_PORT: 3306
    ports:
      - "8080:8080"
