name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build and run 
      run: |
        docker compose up -d

  unit-test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.18'

    - name: Install Dependencies
      run: go mod download

    - name: Run Unit Tests
      working-directory: backend
      run: go test ./...

  docker-publish:
    needs: unit-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
  
      - name: Tag and push Docker images
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/partidos_de_futbol-backend:latest ./backend
          docker build -t ${{ secrets.DOCKER_USERNAME }}/partidos_de_futbol-frontend:latest ./frontend
          docker build -t ${{ secrets.DOCKER_USERNAME }}/partidos_de_futbol-database:latest ./db
      
          docker push ${{ secrets.DOCKER_USERNAME }}/partidos_de_futbol-backend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/partidos_de_futbol-frontend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/partidos_de_futbol-database:latest



          
