name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Build and run 
      run: |
         docker compose up -d

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build Backend Docker Image for Testing
      run: |
        docker build -t backend-test ./backend
    
    - name: Run Unit Tests in Docker
      run: |
        docker run --rm backend-test go test ./...

  docker-publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
  
      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      
      - name: Tag and push Docker images
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/partidos_de_futbol-backend:latest ./backend
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/partidos_de_futbol-frontend:latest ./frontend
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/partidos_de_futbol-database:latest ./db
          
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/partidos_de_futbol-backend:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/partidos_de_futbol-frontend:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/partidos_de_futbol-database:latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

  publish_to_gcr:
    needs: docker-publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME  }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Log in to GCR
        run: |
          echo '${{ secrets.GCP_SA_KEY }}' > /tmp/keyfile.json
          gcloud auth activate-service-account --key-file=/tmp/keyfile.json
          gcloud auth configure-docker gcr.io

      - name: Tag and push Docker images to GCR
        run: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/partidos_de_futbol-database:latest
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/partidos_de_futbol-frontend:latest
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/partidos_de_futbol-backend:latest
          
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/partidos_de_futbol-backend:latest gcr.io/${{ secrets.GCP_PROJECT_ID }}/google_backend
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/partidos_de_futbol-frontend:latest gcr.io/${{ secrets.GCP_PROJECT_ID }}/google_frontend
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/partidos_de_futbol-database:latest gcr.io/${{ secrets.GCP_PROJECT_ID }}/google_database

          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/google_backend:latest
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/google_frontend:latest
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/google_database:latest



          
