name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  Constructor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Build images
        run: |
          docker-compose build
      - name: start containers
        run: |
          docker-compose up -d
  

  Test:
    needs: Constructor
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Build Backend Docker Image for Testing
        run: |
          docker build -t backend-test ./backend

      - name: Run Unit Tests in Docker
        run: |
          docker run --rm backend-test go test ./...

  Publicacion_Docker:
    needs: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Tag and push Docker images
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/partidos_de_futbol-database:latest ./db
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/partidos_de_futbol-frontend:latest ./frontend
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/partidos_de_futbol-backend:latest ./backend

          docker push ${{ secrets.DOCKERHUB_USERNAME }}/partidos_de_futbol-database:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/partidos_de_futbol-frontend:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/partidos_de_futbol-backend:latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

  Publicacion_Google_Cloud:
    needs: Publicacion_Docker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Log in to GCR
        run: |
          echo '${{ secrets.GCP_SA_KEY }}' > /tmp/keyfile.json
          gcloud auth activate-service-account --key-file=/tmp/keyfile.json
          gcloud auth configure-docker gcr.io

      - name: Tag and push Docker images to GCR
        run: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/partidos_de_futbol-database:latest
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/partidos_de_futbol-frontend:latest
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/partidos_de_futbol-backend:latest

          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/partidos_de_futbol-database:latest gcr.io/${{ secrets.GCP_PROJECT_ID }}/google_database
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/partidos_de_futbol-frontend:latest gcr.io/${{ secrets.GCP_PROJECT_ID }}/google_frontend
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/partidos_de_futbol-backend:latest gcr.io/${{ secrets.GCP_PROJECT_ID }}/google_backend

          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/google_database:latest
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/google_frontend:latest
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/google_backend:latest
          
  Implementacion_Nube:
    needs: Publicacion_Google_Cloud
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Google Cloud project and authenticate
        run: |
          echo '${{ secrets.GCP_SA_KEY }}' > /tmp/keyfile.json
          gcloud auth activate-service-account --key-file=/tmp/keyfile.json
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          gcloud config set run/region us-central1

      - name: Import SQL file to Cloud SQL
        run: |
          gcloud --quiet sql import sql ${{ secrets.INSTANCE_ID }} gs://bd_temp/fifa.sql

      - name: Deploy frontend service to Cloud Run
        run: |
          gcloud run deploy partidos-de-futbol-frontend \
            --image=gcr.io/${{ secrets.GCP_PROJECT_ID }}/google_frontend:latest \
            --platform=managed \
            --allow-unauthenticated \
            --memory=4Gi \
            --cpu=2 \
            --port=3000

      - name: Deploy backend service to Cloud Run
        run: |
          gcloud run deploy partidos-de-futbol-backend \
            --image=gcr.io/${{ secrets.GCP_PROJECT_ID }}/google_backend:latest \
            --platform=managed \
            --allow-unauthenticated \
            --memory=8Gi \
            --cpu=4 \
            --port=4000 \
            --add-cloudsql-instances=${{ secrets.GCP_PROJECT_ID }}:${{ secrets.REGION }}:${{ secrets.INSTANCE_ID }} \
            --set-env-vars=DB_HOST=${{ secrets.DB_HOST }},DB_PORT=3306,DB_NAME=${{ secrets.DB_NAME }},DB_USER=${{ secrets.DB_USER }},DB_PASSWORD=${{ secrets.DB_PASSWORD }}
